<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use CodeIgniter\I18n\Time;

class ProductSeeder extends Seeder
{
    public function run()
    {
        try {
            $data = [
                [
                    'name' => 'Kemeja Batik Panjang Pria Motif Parang Barong Flora',
                    'description' => 'Kemeja batik pria lengan panjang dengan motif parang dihiasi dengan motif flora. Motif yang elegan dan kain yang nyaman dipakai.',
                    'price' => 307000,
                    'stock' => 450,
                    'image' => 'kemeja_barong_flora.jpeg',
                    'category_id' => 1,
                    'product_type' => 'baju',
                    'created_at' => Time::now(),
                    'updated_at' => Time::now(),
                ],
                [
                    'name' => 'Kemeja Batik Panjang Pria Katun Tulis Pola',
                    'description' => 'Kemeja batik tulis pria lengan panjang dengan pola geometris dan sentuhan flora. ',
                    'price' => 575000,
                    'stock' => 250,
                    'image' => 'kemeja_tulis_pola.jpeg',
                    'category_id' => 1,
                    'product_type' => 'baju',
                    'created_at' => Time::now(),
                    'updated_at' => Time::now(),
                ],
                [
                    'name' => 'Kemeja Batik Panjang Pria Barong Flora Biru Pekalongan',
                    'description' => 'Kemeja batik pria lengan panjang dengan pola geometris dan sentuhan flora. ',
                    'price' => 305000,
                    'stock' => 250,
                    'image' => 'kemeja_barong_biru_pendek.jpeg',
                    'category_id' => 1,
                    'product_type' => 'baju',
                    'created_at' => Time::now(),
                    'updated_at' => Time::now(),
                ],
                [
                    'name' => 'Kemeja Batik Panjang Pria Parang Rusak Lereng Coklat Solo',
                    'description' => 'Kemeja batik tulis pria lengan panjang bermotif Parang Rusak Lereng berpadu aksen flora dan geometris kontemporer. ',
                    'price' => 280000,
                    'stock' => 330,
                    'image' => 'kemeja_parang_rusak_solo.jpeg',
                    'category_id' => 1,
                    'product_type' => 'baju',
                    'created_at' => Time::now(),
                    'updated_at' => Time::now(),
                ],
                [
                    'name' => 'Kemeja Batik Pendek Pria Barong Flora Biru Pekalongan',
                    'description' => 'Kemeja batik pria lengan pendek dengan pola geometris dan sentuhan flora. ',
                    'price' => 287000,
                    'stock' => 250,
                    'image' => 'kemeja_barong_biru_panjang.jpeg',
                    'category_id' => 1,
                    'product_type' => 'baju',
                    'created_at' => Time::now(),
                    'updated_at' => Time::now(),
                ],
                [
                    'name' => 'Kemeja Batik Pendek Pria Motif Bangau Biru Pekalongan',
                    'description' => 'Kemeja batik pria lengan pendek bermotif burung bangau terbang, simbol kebebasan dan harapan, berpadu motif flora khas Pekalongan dalam balutan warna biru cerah yang menawan.',
                    'price' => 290000,
                    'stock' => 250,
                    'image' => 'kemeja_bangau_pekalongan.jpg',
                    'category_id' => 1,
                    'product_type' => 'baju',
                    'created_at' => Time::now(),
                    'updated_at' => Time::now(),
                ],
                [
                    'name' => 'Kemeja Batik Pendek Pria Motif Kawung Biru',
                    'description' => 'Kemeja batik pria lengan pendek bermotif kawung berpadu motif burung dalam balutan warna biru dan merah yang menawan.',
                    'price' => 295000,
                    'stock' => 250,
                    'image' => 'kemeja_kawung_biru.jpg',
                    'category_id' => 1,
                    'product_type' => 'baju',
                    'created_at' => Time::now(),
                    'updated_at' => Time::now(),
                ],
                [
                    'name' => 'Kemeja Batik Pendek Pria Motif Kawung Merah',
                    'description' => 'Kemeja batik pria lengan pendek bermotif kawung berpadu motif burung dalam balutan warna merah yang menawan.',
                    'price' => 295000,
                    'stock' => 250,
                    'image' => 'kemeja_kawung_merah.jpg',
                    'category_id' => 1,
                    'product_type' => 'baju',
                    'created_at' => Time::now(),
                    'updated_at' => Time::now(),
                ],
                [
                    'name' => 'Kemeja Batik Pendek Pria Lunar New Year',
                    'description' => 'Kemeja batik pria lengan panjang dengan gaya elegan dalam balutan batik merah cerah yang melambangkan keberuntungan dan kebahagiaan. Dihiasi motif burung garuda yang melambangkan kekuatan dan perlindungan, dipadukan dengan pola geometris yang memberikan kesan modern.',
                    'price' => 314000,
                    'stock' => 250,
                    'image' => 'kemeja_lunar.jpg',
                    'category_id' => 1,
                    'product_type' => 'baju',
                    'created_at' => Time::now(),
                    'updated_at' => Time::now(),
                ],
                [
                    'name' => 'Batik Wanita Motif Truntum Kombinasi Lengan Puff',
                    'description' => 'Tampil anggun dengan batik wanita bermotif Truntum hitam putih yang melambangkan ketulusan dan cinta abadi, dipadukan dengan kombinasi motif klasik pada bagian lengan puff dan pinggang. Cocok untuk acara formal, kondangan, maupun kantor dengan nuansa elegan dan modern.',
                    'price' => 249000,
                    'stock' => 315,
                    'image' => 'batik_wanita_truntum_lengan_puff.jpeg',
                    'category_id' => 2,
                    'product_type' => 'baju',
                    'created_at' => Time::now(),
                    'updated_at' => Time::now(),
                ],
                [
                    'name' => 'Batik Wanita Kombinasi Lurik dan Motif Kupu',
                    'description' => 'Blouse batik wanita dengan desain kombinasi lurik klasik dan motif kupu-kupu elegan bernuansa ungu. Cocok untuk tampil kasual maupun semi-formal dengan kesan manis dan tetap etnik. Potongan nyaman untuk digunakan seharian.',
                    'price' => 179000,
                    'stock' => 220,
                    'image' => 'batik_wanita_kombinasi_lurik_kupu.jpg',
                    'category_id' => 2,
                    'product_type' => 'baju',
                    'created_at' => Time::now(),
                    'updated_at' => Time::now(),
                ],
                [
                    'name' => 'Setelan Batik Wanita Kasual Motif Parang dan Flora',
                    'description' => 'Setelan batik wanita dengan atasan lengan pendek motif flora kombinasi stripe putih elegan, dipadukan dengan bawahan motif parang warna maroon yang anggun. Cocok untuk acara santai, kerja, atau arisan dengan tampilan etnik modern yang nyaman dan stylish.',
                    'price' => 279000,
                    'stock' => 125,
                    'image' => 'setelan_batik_wanita_parang_flora.jpg',
                    'category_id' => 2,
                    'product_type' => 'baju',
                    'created_at' => Time::now(),
                    'updated_at' => Time::now(),
                ],
                [
                    'name' => 'Tunik Batik Wanita Motif Biru Pastel',
                    'description' => 'Tunik batik wanita dengan motif bunga biru pastel yang lembut, dilengkapi aksen renda polos di bagian samping untuk memberikan kesan anggun dan modern. Cocok untuk acara formal maupun kasual, memberikan tampilan feminin dan tetap nyaman digunakan seharian.',
                    'price' => 239000,
                    'stock' => 185,
                    'image' => 'tunik_batik_wanita_biru_pastel.jpg',
                    'category_id' => 2,
                    'product_type' => 'baju',
                    'created_at' => Time::now(),
                    'updated_at' => Time::now(),
                ],
                [
                    'name' => 'Dress Batik Wanita Coklat Motif Parang Lengan Renda',
                    'description' => 'Dress batik wanita dengan motif Parang klasik warna coklat elegan, dilengkapi detail lengan renda yang memberi sentuhan feminin dan anggun. Cocok untuk acara kondangan, kerja, maupun casual formal, memberikan kesan etnik modern yang nyaman digunakan seharian.',
                    'price' => 299000,
                    'stock' => 140,
                    'image' => 'dress_batik_wanita_parang_renda.jpg',
                    'category_id' => 2,
                    'product_type' => 'baju',
                    'created_at' => Time::now(),
                    'updated_at' => Time::now(),
                ],
                [
                    'name' => 'Dress Batik Wanita Motif Parang Modern Lengan Cap',
                    'description' => 'Dress batik wanita dengan motif Parang modern perpaduan warna hitam, abu, dan merah maroon, dilengkapi detail layer pada bagian dada yang memberikan kesan anggun dan unik. Cocok untuk acara kondangan, kerja, maupun semi-formal dengan tetap mempertahankan sentuhan etnik elegan.',
                    'price' => 315000,
                    'stock' => 180,
                    'image' => 'dress_batik_wanita_parang_modern.jpg',
                    'category_id' => 2,
                    'product_type' => 'baju',
                    'created_at' => Time::now(),
                    'updated_at' => Time::now(),
                ],
                [
                    'name' => 'Tunik Batik Wanita Motif Parang dan Flora',
                    'description' => 'Tunik batik wanita dengan motif parang berpadu flora klasik dengan warna dasar cokelat dan merah, cocok untuk acara formal maupun kasual dengan nuansa anggun dan nyaman.',
                    'price' => 259000,
                    'stock' => 180,
                    'image' => 'tunik_batik_wanita_parang_flora.jpg',
                    'category_id' => 2,
                    'product_type' => 'baju',
                    'created_at' => Time::now(),
                    'updated_at' => Time::now(),
                ],
            ];
            $this->db->table('products')->insertBatch($data);
        } catch (\Exception $e) {
            echo 'Terjadi Kesalahan: ', $e->getMessage();
        }
    }
}
